version: '3'
services:
  finance:
    volumes:
      - "./:/app" 
    build:
      context: .
    image: test_env:latest
    restart: always
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=all
    